version: "3"

services:
  simple-docker-cleaner:
    build:
      context: .
      #network: host
    #command: day
    #command: 95%
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always